### ISSUE TITLE
Stopped working due to the Chamberlain MyQ API change

### ISSUE THREAD

**Issue by ashokaiyar** [thoward1234/Hubitat-myQ#6]
The same issue that has affected the Home Assistant and Homebridge integrations today. There are more details here:

https://github.com/arraylabs/pymyq/issues/22

**Comment by ryancasler** [comment]
Mine is working fine.  However mine is Liftmaster.  Also, there is a solution on the other thread.

**Comment by ashokaiyar** [comment]
Looks like API version 5 took effect today/yesterday. Things stopped working again - with a login failure.

**Comment by Danzig69** [comment]
i was unable to open or close my liftmaster garage door today and yesterday with Hubitat. In the Apps MyQ Lite V3.0.2 i see my email adresse, put the password, select liftmaster, click next and i received this error : Unexpected Error
An unexpected error has occurred trying to load the app. Check Logs for more information.
Error: Bad Request

It was working a couple of day ago. 
On this web site https://www.myliftmaster.com i can login so my email/password are good. i can see my device. But the web site said : In order to provide the best myQ experience, this web login will no longer be supported.
Maybe this is one of the cause?

Hubitat Logs : groovyx.net.http.HttpResponseException: Bad Request on line 922 (prefListDevices)

**Comment by jniedens** [comment]
Same problem. Any chance someone smarter then me knows how to fix this or are we just screwed?

**Comment by ashokaiyar** [comment]
@Danzig69 @jniedens and anyone else who's here **because MyQ Lite no longer works on Hubitat**:

The solution is to install a new version of the MyQ Lite app and driver. Details are in this post (and the ones following it) from community.hubitat.com:

https://community.hubitat.com/t/chamberlain-myq-garage-door-support/3550/289

You will have to delete the original app and driver and re-create the MyQ device using the app and driver linked to in that post.

**Comment by ashokaiyar** [comment]
Because there's a new app and driver for MyQ integration into Hubitat, I am closing this issue.
